# Generated by Django 3.0.2 on 2020-08-07 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0003_auto_20200806_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AM', 'Amakara'), ('AS', 'Amasiteri'), ('IM', 'Imbaho'), ('IB', 'Ibiti')], max_length=2, verbose_name='Ubwoko')),
                ('measure', models.CharField(blank=True, default='Amasiteri', max_length=50, verbose_name='Urugero')),
                ('minimum', models.IntegerField(default=10, verbose_name='Ingano ntoya')),
            ],
        ),
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=20)),
                ('plate', models.CharField(max_length=10)),
                ('max_q', models.PositiveIntegerField(blank=True, null=True)),
                ('driver', models.CharField(max_length=255)),
                ('driver_tel', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='transportpermit',
            options={'verbose_name': 'transport permit', 'verbose_name_plural': 'transport permits'},
        ),
        migrations.RemoveField(
            model_name='transportpermit',
            name='address',
        ),
        migrations.RemoveField(
            model_name='transportpermit',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='transportpermit',
            name='driver_tel',
        ),
        migrations.RemoveField(
            model_name='transportpermit',
            name='forest_owner',
        ),
        migrations.RemoveField(
            model_name='transportpermit',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='transportpermit',
            name='location',
        ),
        migrations.RemoveField(
            model_name='transportpermit',
            name='names',
        ),
        migrations.RemoveField(
            model_name='transportpermit',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='transportpermit',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='transportpermit',
            name='transport_vehicle',
        ),
        migrations.RemoveField(
            model_name='transportpermit',
            name='vehicle_max_q',
        ),
        migrations.RemoveField(
            model_name='transportpermit',
            name='vehicle_plate',
        ),
        migrations.AlterField(
            model_name='transportpermit',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permit.Mayor'),
        ),
        migrations.AlterField(
            model_name='transportpermit',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Nomero'),
        ),
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255, verbose_name='Amazina')),
                ('nid', models.CharField(blank=True, max_length=16, verbose_name='Indangamuntu')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permit.Address')),
                ('r_cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permit.Cell')),
                ('r_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='permit.District')),
                ('r_province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='permit.Province')),
                ('r_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='permit.Sector')),
                ('r_village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permit.Village')),
            ],
        ),
        migrations.CreateModel(
            name='OriginLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=30, null=True)),
                ('l_cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permit.Cell')),
                ('l_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permit.District')),
                ('l_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permit.Province')),
                ('l_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permit.Sector')),
                ('l_village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permit.Village')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('d_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permit.District')),
                ('d_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permit.Province')),
            ],
        ),
        migrations.AddField(
            model_name='transportpermit',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permit.Destination'),
        ),
        migrations.AddField(
            model_name='transportpermit',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permit.OriginLocation'),
        ),
        migrations.AddField(
            model_name='transportpermit',
            name='requestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permit.Requestor'),
        ),
        migrations.AddField(
            model_name='transportpermit',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='permit.TransportVehicle'),
        ),
        migrations.AlterField(
            model_name='transportpermit',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='permit.Category'),
        ),
    ]
