# Generated by Django 3.0.2 on 2020-08-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0005_auto_20200807_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestor',
            name='address',
        ),
        migrations.AddField(
            model_name='requestor',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='telephone'),
        ),
        migrations.AlterField(
            model_name='transportvehicle',
            name='driver',
            field=models.CharField(max_length=255, verbose_name='Umushoferi'),
        ),
        migrations.AlterField(
            model_name='transportvehicle',
            name='driver_tel',
            field=models.CharField(max_length=255, verbose_name="Nimero y'umushoferi"),
        ),
        migrations.AlterField(
            model_name='transportvehicle',
            name='max_q',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ibyo itwara'),
        ),
        migrations.AlterField(
            model_name='transportvehicle',
            name='plate',
            field=models.CharField(max_length=10, verbose_name='Plake'),
        ),
        migrations.AlterField(
            model_name='transportvehicle',
            name='vehicle',
            field=models.CharField(max_length=20, verbose_name='Ubwoko'),
        ),
    ]
