# Generated by Django 3.0.6 on 2020-08-12 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0006_auto_20200807_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originlocation',
            name='l_village',
        ),
        migrations.RemoveField(
            model_name='requestor',
            name='r_village',
        ),
        migrations.AlterField(
            model_name='cell',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='permit.Sector'),
        ),
        migrations.AlterField(
            model_name='requestor',
            name='nid',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='Indangamuntu'),
        ),
        migrations.AlterField(
            model_name='transportvehicle',
            name='vehicle',
            field=models.CharField(choices=[('FS', 'FUSSO'), ('BN', 'BEN'), ('DH', 'DAIHATSU')], default='FS', max_length=20, verbose_name='Ubwoko'),
        ),
        migrations.AlterField(
            model_name='village',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='permit.Cell'),
        ),
    ]
