# Generated by Django 3.0.6 on 2020-08-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0007_auto_20200812_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HarvestingPermit',
        ),
    ]
