# Generated by Django 3.0.4 on 2020-08-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_officer'),
        ('permit', '0009_auto_20200813_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportpermit',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Officer'),
        ),
    ]
