# Generated by Django 3.0.6 on 2020-08-13 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permit', '0008_delete_harvestingpermit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255)),
                ('width', models.FloatField(blank=True, default=13, help_text='Andika ubugari muri centimeter', null=True, verbose_name='Umurambararo')),
                ('height', models.FloatField(blank=True, default=15, help_text='Andika uburebure muri metero', null=True, verbose_name='Uburebure')),
                ('number', models.PositiveIntegerField(blank=True)),
                ('upi', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictTaxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('bank', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FonerwaTaxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('bank', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('distance_district', models.FloatField(blank=True)),
                ('construction_species', models.ManyToManyField(blank=True, related_name='forests', to='harvest.ConstructionSpecies')),
                ('f_cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permit.Cell', verbose_name='Akagali')),
                ('f_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='permit.District', verbose_name='Akarere')),
                ('f_province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='permit.Province', verbose_name='Intara')),
                ('f_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='permit.Sector', verbose_name='Umurenge')),
            ],
        ),
        migrations.CreateModel(
            name='HarvestingGuidelines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(auto_created=True, blank=True)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TimberSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255)),
                ('width', models.FloatField(blank=True, default=13, help_text='Andika ubugari muri centimeter', null=True, verbose_name='Umurambararo')),
                ('height', models.FloatField(blank=True, default=15, help_text='Andika uburebure muri metero', null=True, verbose_name='Uburebure')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HPRequestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(1, 'Leta'), (2, 'Akarere'), (3, 'Umurenge'), (4, 'Umuturage')], default=4, max_length=2)),
                ('names', models.CharField(max_length=255, verbose_name='Amazina')),
                ('nid', models.CharField(blank=True, max_length=21, null=True, verbose_name='Indangamuntu')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='telephone')),
                ('r_cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permit.Cell', verbose_name='Akagali')),
                ('r_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='permit.District', verbose_name='Akarere')),
                ('r_province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='permit.Province', verbose_name='Intara')),
                ('r_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='permit.Sector', verbose_name='Umurenge')),
            ],
        ),
        migrations.CreateModel(
            name='HarvestingPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_approved', models.DateField()),
                ('dfnro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('forest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='harvest.Forest')),
                ('guidelines', models.ManyToManyField(to='harvest.HarvestingGuidelines')),
            ],
        ),
        migrations.AddField(
            model_name='forest',
            name='timber_species',
            field=models.ManyToManyField(blank=True, to='harvest.TimberSpecies'),
        ),
    ]
