# Generated by Django 3.0.6 on 2020-08-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forest',
            old_name='distance_district',
            new_name='distance',
        ),
        migrations.RemoveField(
            model_name='constructionspecies',
            name='upi',
        ),
        migrations.AddField(
            model_name='forest',
            name='upi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
