# Generated by Django 3.0.6 on 2020-08-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0002_auto_20200813_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionspecies',
            name='species',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='harvestingpermit',
            name='date_approved',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='harvestingpermit',
            name='guidelines',
            field=models.ManyToManyField(blank=True, to='harvest.HarvestingGuidelines'),
        ),
        migrations.AlterField(
            model_name='hprequestor',
            name='category',
            field=models.IntegerField(choices=[(1, 'Leta'), (2, 'Akarere'), (3, 'Umurenge'), (4, 'Umuturage')], default=4, verbose_name='Usaba'),
        ),
    ]
