# Generated by Django 3.0.6 on 2020-08-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0004_auto_20200813_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestingpermit',
            name='requestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits', to='harvest.HPRequestor', verbose_name='Usaba'),
        ),
    ]
