# Generated by Django 3.0.4 on 2020-08-20 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0009_auto_20200813_2024'),
        ('user', '0003_auto_20200812_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dfnro', to='permit.District')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dfnro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
