# Generated by Django 3.0.4 on 2020-08-20 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_dfnro',
        ),
        migrations.AlterField(
            model_name='officer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dfnro', to=settings.AUTH_USER_MODEL),
        ),
    ]
